/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket100.xml
 */
package sul.protocol.pocket100.play;

import sul.utils.*;

public class BlockEvent extends Packet {

	public static final byte ID = (byte)28;

	public static final boolean CLIENTBOUND = true;
	public static final boolean SERVERBOUND = false;

	public sul.protocol.pocket100.types.BlockPosition position;
	public int[] data = new int[2];

	public BlockEvent() {}

	public BlockEvent(sul.protocol.pocket100.types.BlockPosition position, int[] data) {
		this.position = position;
		this.data = data;
	}

	@Override
	public int length() {
		int length=position.length() + 1; for(int zgf0yq:data){ length+=Buffer.varintLength(zgf0yq); } return length;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeBigEndianByte(ID);
		this.writeBytes(position.encode());
		for(int zgf0yq:data){ this.writeVarint(zgf0yq); }
		return this._buffer;
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		readBigEndianByte();
		position=new sul.protocol.pocket100.types.BlockPosition(); position._index=this._index; position.decode(this._buffer); this._index=position._index;
		final int bgrhdge=2; data=new int[bgrhdge]; for(int zgf0yq=0;zgf0yq<data.length;zgf0yq++){ data[zgf0yq]=this.readVarint(); }
	}

	public static BlockEvent fromBuffer(byte[] buffer) {
		BlockEvent ret = new BlockEvent();
		ret.decode(buffer);
		return ret;
	}

}
