/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
package sul.utils;

public class Enchantment {

	public final byte id;
	public final short level;

	public Enchantment(byte id, short level) {
		this.id = id;
		this.level = level;
	}

}
