/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
package sul.utils;

public class Item {

	public final String name;
	public final int id, meta;
	public final Enchantment[] enchantments;

	public Item(String name, int id, int meta, Enchantment[] enchantments) {
		this.name = name;
		this.id = id;
		this.meta = meta;
		this.enchantments = enchantments;
	}

}
