/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
package sul.utils;

public class MetadataException extends RuntimeException {

	private static final long serialVersionUID = 0x5EL;

	public MetadataException(String reason) {
		super(reason);
	}

}
