/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
package sul.utils;

public final class Tuples {

	private Tuples() {}

	public static class ByteXZ {

		public byte x, z;

		public ByteXZ() {}

		public ByteXZ(byte x, byte z) {
			this.x = x;
			this.z = z;
		}

	}

	public static class DoubleXYZ {

		public double x, y, z;

		public DoubleXYZ() {}

		public DoubleXYZ(double x, double y, double z) {
			this.x = x;
			this.y = y;
			this.z = z;
		}

	}

	public static class ShortXYZ {

		public short x, y, z;

		public ShortXYZ() {}

		public ShortXYZ(short x, short y, short z) {
			this.x = x;
			this.y = y;
			this.z = z;
		}

	}

	public static class IntXZ {

		public int x, z;

		public IntXZ() {}

		public IntXZ(int x, int z) {
			this.x = x;
			this.z = z;
		}

	}

	public static class IntXYZ {

		public int x, y, z;

		public IntXYZ() {}

		public IntXYZ(int x, int y, int z) {
			this.x = x;
			this.y = y;
			this.z = z;
		}

	}

	public static class FloatXYZ {

		public float x, y, z;

		public FloatXYZ() {}

		public FloatXYZ(float x, float y, float z) {
			this.x = x;
			this.y = y;
			this.z = z;
		}

	}

	public static class ByteXYZ {

		public byte x, y, z;

		public ByteXYZ() {}

		public ByteXYZ(byte x, byte y, byte z) {
			this.x = x;
			this.y = y;
			this.z = z;
		}

	}

	public static class DoubleXZ {

		public double x, z;

		public DoubleXZ() {}

		public DoubleXZ(double x, double z) {
			this.x = x;
			this.z = z;
		}

	}

}
