# DragonProxy Configuration (31/03/19)
# https://github.com/DragonetMC/DragonProxy

locale: 'EN'

# The IP and port the proxy will listen for connections on
# '0.0.0.0' will bind to all IP addresses available on your device
bind-address: '0.0.0.0'
bind-port: 19132

# The MOTD that will be shown on the MCPE server list
motd: 'DragonProxy'
motd2: 'https://github.com/DragonetMC/DragonProxy'

# The maximum amount of players that can join the proxy
max-players: 1

# The IP and port of the remote server to connect to
# TODO: Add support for multiple servers
remote-address: '127.0.0.1'
remote-port: 25566

#java login credentials

#will this use java credentials?
java: false
password: ""
username: ""

# TODO
#remote-servers:
#  local:
#    address: '127.0.0.1'
#    port: 25566
#    default: true
