/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket101.xml
 */
package sul.protocol.pocket101.play;

import sul.utils.*;

/**
 * Shows the end credits to the player. They are always skippable client-side and a
 * packet of this type is sent back by the client when the credits are skipped or finished.
 */
public class ShowCredits extends Packet {

	public static final byte ID = (byte)76;

	public static final boolean CLIENTBOUND = true;
	public static final boolean SERVERBOUND = true;

	@Override
	public int length() {
		return 1;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeBigEndianByte(ID);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		readBigEndianByte();
	}

	public static ShowCredits fromBuffer(byte[] buffer) {
		ShowCredits ret = new ShowCredits();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "ShowCredits()";
	}

}
