/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/bedrock137.xml
 */
package org.dragonet.protocol.type.chunk;

import org.dragonet.common.utilities.BinaryStream;

public class ExtraData {

    public int key;
    public short value;

    public ExtraData() {

    }

    public ExtraData(int key, short value) {
        this.key = key;
        this.value = value;
    }

    public void encode(BinaryStream out) {
        out.putVarInt(key);
        out.putLShort(value);
    }

    public void decode(BinaryStream in) {
        key = (int) in.getUnsignedVarInt();
        value = (short) in.getLShort();
    }

    public String toString() {
        return "ExtraData(key: " + this.key + ", value: " + this.value + ")";
    }
}
